### ISSUE TITLE
Why? What? Who? How? 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-wireframing#1]
# _Why_?

In many cases sketching a wireframe of an idea is the _fastest_ way to share that idea with other people. A wireframe is also one of the best ways of developing/expanding your own thinking/understanding of the idea at _minimal_ cost. 

# _What_?

Wireframing is fancy way of saying "rough sketching". The objective is not to have a _pixel-perfect_ rendering of the idea but rather to draw the _minimum_ necessary to communicate. A wireframe should be as simple as possible to convey the concept to the observer without clutter or confusion. 

+ [x] Insert an example of a **stick-person** to show what the most elemental drawing looks like. 

If you know how to draw a stick-person (_and most [5 year olds can](https://www.zerotothree.org/resources/305-learning-to-write-and-draw) do this very well!_) then you already know how to draw a wireframe. 

# _Who_? 

+ [x] insert picture of a person drawing a wireframe.

This skill is for _anyone_ who has an idea that they need/want to communicate with others.
It's for _everyone_ from primary school children wanting to share their first idea to budding Entrepreneurs hoping to change the world! If you have a spark in your _mind_ and want to _capture_ it, keep reading! By the end of this 25 minute block you will be well on your way to creating wireframes for your ideas!

# _How_?

Our goal is to take people through "5 stages of wireframing" by dividing this tutorial/guide into two parts:

## Part 1: The Fundamentals

1. **Paper-based sketch** for the absolute minimum idea capture!
  + [x] Give 3 examples of wireframes starting with the most simple one you can think of and working your way up to a "UX Flow" where you illustrate "progression" from one "screen" to the next. 

2. **Sharing/Showing** your sketch to people.
  + [ ] What is the most effective way to share your sketch with others?
  + [ ] If the sketch is paper-based, you already have a piece of paper (_or page in your notebook_) that you can share with people IRL! Or you can take a snap of the paper-sketch and share that with people who are not physically co-located with you. 
  + [ ] If the sketch is done using a digital tool, your first step is seeing if the tool has "sharing" built-in.
    + [ ] Google Slides has sharing/co-editing built-in. that's why we recommend it for beginners. I will have a decent example of a Google Slides based wireframe to share with you at this point in the Tutorial. So don't spend too much time thinking about an _example_. Just move on to the "basics" of Google Slides. 

3. **Basic Tools: Google Slides**: https://www.google.co.uk/slides/about/
  + [ ] If you find good _official_ docs/videos for learning Google Slides UI, link to them!

4. More "**advanced**" (_than Google Slides but still **_free_) wireframing tools** 
+ [ ] Research required: what is the best ***free*** online wireframing tool?
  + [x] Prepare a shortlist of the best _free_ wrireframing tools that exist.
  + [x] Explain the pros and cons of each tool. 
  + [x] Give prominence to the Open Source, but at this stage prioritise ease-of-use to the person creating the sketch as opposed to the philosophy of code openness. 
  + [ ] Reach a conclusive recommendation for the 

If we can write this is in our "traditional" (_self-contained_) `README.md` style, it will be a _really_ good start. 

## Part 2: Professional Tools

5. What are the "Top 5" paid-for wireframe tools/services that professionals use to capture their ideas, share them with their teams and collect collaborative feedback?
+ [ ] Research required: what are the "Top 5" (_or however many you chose to look at & compare_) "Pro" level Wireframing Tools/Apps that allow for low/medium (_or even high_) fidelity wireframes to be drawn, shared and collaboratively improved, e.g: Figma 
+ [ ] Write this in a _separate_ `advanced-wrireframing-tools.md` doc so that be published as a _separate_ "Part 2 Blog Post".

> Note: this post will cross-link to our (_as yet unwritten_) post on Open Source. Crucially, it will link to the fact that that _most_ SaaS products are _closed_ source because significant value is being captured which in turn leads to more investment ... I will elaborate on this later; for now focus on this task: How to do Wireframing! 👍

**Comment by nelsonic** [comment]
@Cleop how do you feel about taking the lead on this?

**Comment by nelsonic** [comment]
@Cleop as _soon_ as you wrap up your _current_ task on Club Soda please take a look at this. Thanks! ✨

**Comment by Cleop** [comment]
@nelsonic, having reread your comment above:
> as soon as you wrap up your current task on Club Soda please take a look at this
Are you happy for me to look at this with other CS issues still in the sprint column? Previously I thought I'd move on to this after I'd cleared the sprint column but I realised you said 'your current task on CS'.

**Comment by nelsonic** [comment]
@Cleop _good_ question. 
apologies, "current" isn't _clear_, I should have been more specific to avoid doubt. 

On the basis that there are still a few **`priority-2`** (_high priority_) items in the "Sprint 4" column: https://github.com/club-soda/club-soda-guide/projects/1 I suggest that you pick off a couple more of those CS issues/tasks so that we can "wrap up" CS as much as possible to _delight_ the CS users/PO. 

When you get to the "UX" issue (["***Improving the UX of uploading pictures***"](https://github.com/club-soda/club-soda-guide/issues/317) which is **`P4`**), 
and provided there are no **`priority-1`** issues demanding your attention, 
The "UX of Uploading Images" is a _really_ good example where a Wireframe/UX flow 
(_that most people can relate to_) would be a good fit for explaining wireframing (_i.e. this task_).

So there is a **symbiosis** between creating a **_generic/re-useable_ learning resource** + code
that _applies_ to the **client project** and will be _immediately_ relevant to Time/Activity Tracking
(_the ability to **upload images** is a feature people "don't know they need/want", 
until they see it's applicability/usefulness and won't want to live without it!_)

# _Next Action_ 

+ [ ] Focus on _finishing_ CS so that the PO/users does not have to _wait_ for features that are easily implemented. (_or "bugs" that are simple - albeit time-consuming - to fix_) 🚧 
+ [ ] Check-in with @iteles during standup and/or retro to _confirm_ how many more of the issues in the backlog we are going to pick off before considering the MVP "ready" for extended UX testing. 📱 
+ [ ] Once Inês/PO _confirms_ that they are "happy" with the state of the CS App/Site,
check you own _personal_ backlog (_assigned issues & pull requests_) to confirm that there is nothing "important" or "urgent" that should take precedence over writing a tutorial/how-to/example. 📥 
+ [ ] With your "inbox" cleared, go for a walk/run in the fresh air to clear your mind. ☀️ 
+ [ ] ***`.then`*** start work on ***`this`*** task with _all_ your creative energy. ✅

**Comment by Cleop** [comment]
> * Give 3 examples of wireframes starting with the most simple one you can think of and working your way up to a "UX Flow" where you illustrate "progression" from one "screen" to the next.

@nelsonic - for this point, what do you mean in terms of 'progression'? Do you mean progressing from low fidelity to high fidelity or from an initial idea and then getting user feedback so the design/feature is refined more. Or something totally different?

**Comment by nelsonic** [comment]
@Cleop good clarifying question. 👍 
What I had in mind with regards to "progression" in the context above:
![image](https://user-images.githubusercontent.com/194400/52779629-74600200-3040-11e9-9e9c-b2439476f38b.png)
is _literally_ showing how a _user_ "progresses" through the application. 
i.e. how they go from one "screen" (_or "view"_) to the next one. e.g:
![ux-progression](https://user-images.githubusercontent.com/194400/52779767-bc7f2480-3040-11e9-827c-b1ce9dad1b18.png)

In the _first_ ("Fundamentals") part of this quest, just use the simplest tool you can find and show a "flow" through your chosen "user story". 

Try to avoid hand-drawing the screens in a _tutorial_ unless the tutorial is _about_ hand-sketching.
Sketching _absolutely_ has it's "place" when "brainstorming" ideas in a collaborative session,
![image](https://user-images.githubusercontent.com/194400/52780226-a1f97b00-3041-11e9-892e-e3fc29279db2.png)
Hand-sketching is perfect for _quickly discussing_ an idea in-person or via remote collaboration.

![image](https://user-images.githubusercontent.com/194400/52780168-89896080-3041-11e9-820c-0ba109ed6a21.png)
but when it comes to _communicating_ with the rest of the team, realistic (but low-fidelity) straight lines and **_legible fonts_** are _much_ more effective because people are less likely to "misinterpret" things.
![sitemap-flow](https://user-images.githubusercontent.com/194400/52780737-cefa5d80-3042-11e9-907e-1ab82c301b4b.jpg)
source: https://speckyboy.com/collection-inspiring-sitemaps-user-flow-maps

**Comment by Cleop** [comment]
### WIP - Editing this version
# _Why_?

In many cases sketching a wireframe of an idea is the _fastest_ way to share that idea with other people. A wireframe is also one of the best ways of developing/expanding your own thinking/understanding of the idea at _minimal_ cost. 

# _What_?

Wireframing is fancy way of saying "rough sketching". The objective is not to have a _pixel-perfect_ rendering of the idea but rather to draw the _minimum_ necessary to communicate. A wireframe should be as simple as possible to convey the concept to the observer without clutter or confusion. 

![stick person](https://user-images.githubusercontent.com/16775804/52957993-fd51a300-338a-11e9-8400-c678f1657924.jpg)

If you know how to draw a stick-person (_and most [5 year olds can](https://www.zerotothree.org/resources/305-learning-to-write-and-draw) do this very well!_) then you already know how to draw a wireframe. 

# _Who_? 

![drawing wireframe](https://user-images.githubusercontent.com/16775804/52957675-2160b480-338a-11e9-9af0-eb09b6a9c1b0.jpg)

This skill is for _anyone_ who has an idea that they need/want to communicate with others.
It's for _everyone_ from primary school children wanting to share their first idea to budding Entrepreneurs hoping to change the world! If you have a spark in your _mind_ and want to _capture_ it, keep reading! By the end of this 25 minute block you will be well on your way to creating wireframes for your ideas!


# _How_?

Our goal is to take people through "5 stages of wireframing" by dividing this tutorial/guide into two parts:

## Part 1: The Fundamentals

1. **Paper-based sketch** for the absolute minimum idea capture!
  + [ ] Give 3 examples of wireframes starting with the most simple one you can think of and working your way up to a "UX Flow" where you illustrate "progression" from one "screen" to the next. 

2. **Sharing/Showing** your sketch to people.
  + What is the most effective way to share your sketch with others?
  + If the sketch is paper-based, you already have a piece of paper (_or page in your notebook_) that you can share with people IRL! Or you can take a snap of the paper-sketch and share that with people who are not physically co-located with you. 
  + If the sketch is done using a digital tool, your first step is seeing if the tool has "sharing" built-in.
    + Google Slides has sharing/co-editing built-in, that's why we recommend it for beginners.

3. **Basic Tools: Google Slides**: https://www.google.co.uk/slides/about/
  + [ ] If you find good _official_ docs/videos for learning Google Slides UI, link to them!

4. More "**advanced**" (_than Google Slides but still **_free_) wireframing tools** 
+ [ ] Research required: what is the best ***free*** online wireframing tool?
  + [ ] Prepare a shortlist of the best _free_ wrireframing tools that exist.
  + [ ] Explain the pros and cons of each tool. 
  + [ ] Give prominence to the Open Source, but at this stage prioritise ease-of-use to the person creating the sketch as opposed to the philosophy of code openness. 
  + [ ] Reach a conclusive recommendation for the

**Comment by Cleop** [comment]
Moqups -
Free Plan offers 1 project (limited to 250 objects) and 5MB of storage or premium tier is free to NGOs and students.
It’s fast, easy to use and works without a browser plug-in. Screens and buttons can be linked so you can publish a demonstration for your clients to view and use. Images can also be exported for specification diagrams.

Google drive drawings -
While Google Drawings is not a wireframing application, it can be used for simple screen mock-ups. The tool is fast, offers collaboration and is an absolute joy to use. Diagrams can be output to a range of file types and embedded within other Google Drive documents.

https://wireframe.cc/

**Comment by Cleop** [comment]
WIP -

## Part 2: Professional Tools
1. What are the "Top 5" paid-for wireframe tools/services that professionals use to capture their ideas, share them with their teams and collect collaborative feedback?

* [ ]  Research required: what are the "Top 5" (_or however many you chose to look at & compare_) "Pro" level Wireframing Tools/Apps that allow for low/medium (_or even high_) fidelity wireframes to be drawn, shared and collaboratively improved, e.g: Figma
* [ ]  Write this in a _separate_ `advanced-wrireframing-tools.md` doc so that be published as a _separate_ "Part 2 Blog Post".

**Comment by nelsonic** [comment]
> "_I have not found open source wireframing tools_" ...

@Cleop could it be worth opening a question _similar_ to this one:
https://stackoverflow.com/questions/3432665/open-source-or-free-wireframe-tools
but on the _appropriate_ forum e.g: https://ux.stackexchange.com

?

**Comment by Cleop** [comment]
Yeah, I tried that SO article, I should have mentioned that in my comment, apologies. 

I didn't know UX stack exchange existed so thanks, I've made a question:
https://ux.stackexchange.com/questions/123919/what-open-source-and-free-wireframing-tools-are-there

**Comment by Cleop** [comment]
- [ ] add MyDraft to the readme

**Comment by nelsonic** [comment]
@cleop is this the question: https://ux.stackexchange.com/questions/123919/what-open-source-and-free-wireframing-tools-are-there ?
