### ISSUE TITLE
Is there a "Holly Grail" of Wire-framing?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-wireframing#2]
The "_holly grail_" of wireframing would allow the product owner to create UI/UX components using drag-and-drop interface which would then produce standards-compliant HTML as close as possible to the view that will be rendered to users. 
There is no shortage of tools that _promise_ this. So far we haven't found one that _delivers_.

# Ideal Feature/Requirement List

+ [ ] _Fully_ Open Source (_on GitHub/GitLab or equivalent SCM_)
+ [ ] Web-based Collaboration so people working on UI/UX can work across geographic bounderies.
+ [ ] All changes to designs/layouts are "non-destructive" and version-controlled (_full rollback-ability_)
+ [ ] Global Map of all "screens" and flow between them.
+ [ ] Permissions to allow stakeholders to view without editing (_if desired_)
+ [ ] Free for basic usage (_**always free** for **open source** projects and **learning**_)
+ [ ] Don't charge "_per user per month_", instead charge a flat fee per project/app.
  > Charging per user creates a "scarcity mindset" where frugal (_pennywise_) biz managers/owners don't want to have an account for each person/user and thus _discourages collaboration_. 
+ [ ] add more if you think of any ...

# Todo

+ [ ] Research available Open Source wireframing tools to see what _already_ exists.
  + [ ] Tools should allow easy standards-compliant HTML export.
+ [ ] Research available _Closed_ Source tools that purport to have the "holly grail" features.

**Comment by nelsonic** [comment]
Designing with Elm
[![image](https://user-images.githubusercontent.com/194400/70473155-647e4680-1ac8-11ea-9fd7-815dedd60646.png)](https://youtu.be/_KUcclVTY8g)
https://youtu.be/_KUcclVTY8g
